### PR TITLE
auto-create notes when using go to definition on missing wikilink

### PR DESCRIPTION
**Pull request by pomdtr**
This feature is inspired by roam research.

### CODE REVIEW

**Comment by RensDimmendaal** [comment]
Nice! I would like to add that it might be nice to:

* Be able to turn this auto-create function off
* If it's on to have (the option for) a confirmation dialog before creating the note

These settings could protect against accidentally creating notes when you make a typo.

**Comment by kortina** [comment]
This is very sweet. I agree with @RensDimmendaal suggestions for the configuration options.

Something like:

- `vscodeMarkdownNotes.createNoteOnGoToDefinitionWhenMissing` (open to a `true` default here but curious what others think)
- and `vscodeMarkdownNotes.confirmCreateNoteOnGoToDefinitionWhenMissing` (probably default to `false` because I feel like if you have this feature on you don't want to have to confirm)

extra credit: undo command for this

**Comment by kortina** [comment]
Just wanted to comment / follow-up on this and say (1) this idea had not even occurred to me since I saw your pull request but (2) now I find myself wishing it existed every time I create a new note.

Would be awesome to get the configuration options added to allow people to turn this off.

Thinking about it some more, I would say:

* `vscodeMarkdownNotes.createNoteOnGoToDefinitionWhenMissing` - default this to `true`
* `vscodeMarkdownNotes.confirmCreateNoteOnGoToDefinitionWhenMissing` - nice to have but not essential for MVP

**Comment by kortina** [comment]
#20 adds the configuration for this and merges it in (w/ minor edits). Live in 0.0.6

**Comment by kortina** [comment]
@pomdtr thanks for working on this. I am pretty excited about this feature and foresee this being my default method for creating new notes.

**Pull request closed without merging**
